### ISSUE TITLE
Generate Mob can generate too many

### ISSUE THREAD

**Issue by rkausch2** [toktic/sr6_gmt#2]
I set it up to generate 4-10 members, and checked "include Lieutenant". It generated 11. I'm guessing that might be because of the additional Lieutenant, but not sure. 
![image](https://user-images.githubusercontent.com/62491852/77241348-818ddf80-6bb6-11ea-8da2-a109ea0aa5af.png)

**Comment by toktic** [comment]
Working as originally intended. The number range determines the number of plain mooks, and the checkboxes for special types add those special types to the final count.
